version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "ok-to-test"

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "ok-to-test"

  - package-ecosystem: "gomod"
    directory: "/hack/tools"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "ok-to-test"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    ignore:
      - dependency-name: "*"
        update-types:
        - "version-update:semver-major"
        - "version-update:semver-minor"
    groups:
      k8s:
        patterns:
        - "k8s.io/*"
        - "sigs.k8s.io/*"
    labels:
      - "ok-to-test"
